### ISSUE TITLE
Hi,有后台管理员的页面吗，还有我老是报跨域的问题，我后端的代码页已经加了@CrossOrigin注解了

### ISSUE THREAD

**Issue by Ethan1i** [MYvLiang/second-hand-trading#1]

**Comment by MYvLiang** [comment]
暂时没有打算做后台管理页面哈。跨域问题我没有使用@CrossOrigin注解，我在WebMvcConfig类配置的，实现了WebMvcConfigurer接口，重写了public void addCorsMappings(CorsRegistry registry) 方法，核心在于.allowedOrigins("http://localhost:8081")  ，可以看看我的写法。前端axios也有一些封装配置。还有一点，有一个版本我将所有url“http://localhost:8080”改成了我部署的域名，不过最新的版本已经改回来了，如果你看的是旧版，可用idea的全局替换功能，替换所有的https://shinytengxvnyun.cn为http://localhost:8080。

**Comment by MYvLiang** [comment]
如果addCorsMappings方法中配置的域名和端口与前端运行的域名和端口一样，还是有跨域报错的话，可以试试用vue cli的代理转发请求。我的朋友做前后端分离的项目时使用我的配置方式依然报错，可能跟一些拦截器有关吧，我也不明白为什么，后来他只能使用代理转发请求暂时解决测试时的跨域问题。

**Comment by Ethan1i** [comment]
嗯，我用了代理转发就好了。之前我把你的addCorsMappings注释掉，然后采用加注解的方式，还是有各种问题。采用代理转发就ok了。我看网上说这个可能是拦截器和WebMvcConfig里面的设置冲突。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SHINY"<notifications@github.com&gt;; 
发送时间: 2021年2月1日(星期一) 下午3:36
收件人: "MYvLiang/second-hand-trading"<second-hand-trading@noreply.github.com&gt;; 
抄送: "风之旅人"<549413546@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MYvLiang/second-hand-trading] Hi,有后台管理员的页面吗，还有我老是报跨域的问题，我后端的代码页已经加了@CrossOrigin注解了 (#1)





 
如果addCorsMappings方法中配置的域名和端口与前端运行的域名和端口一样，还是有跨域报错的话，可以试试用vue cli的代理转发请求。我的朋友做前后端分离的项目时使用我的配置方式依然报错，可能跟一些拦截器有关吧，我也不明白为什么，后来他只能使用代理转发请求暂时解决测试时的跨域问题。
